name: sqlsim

services:
  breastcancer:
    build:
      context: .
      dockerfile: Dockerfile
    
    env_file:
      - .env
    
    volumes:
      - ../../main.sql:/docker-entrypoint-initdb.d/main.sql
      - ./data_preparation.sql:/docker-entrypoint-initdb.d/data_preparation.sql
    
    ports:
      - 5432:5432
